Repository murilopereirame/secompp-pokedex, pull requests merged in 2022-10, with the labels that each got.

#1 init: Atualizado README
  README.md
Labels: documentation, hacktoberfest-accepted

#2 Feature/PKD-1
  .gitignore
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/classes/pokemon.dart
  lib/classes/pokemon_type_color.dart
  lib/classes/type.dart
  lib/components/pokemon_card.dart
  lib/components/type_card.dart
  lib/main.dart
  lib/utils.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement, hacktoberfest-accepted

#3 Feature/PKD-2
  lib/components/pokemon_card.dart
  lib/main.dart
  lib/network.dart
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
  macos/Runner/DebugProfile.entitlements
  macos/Runner/Release.entitlements
  pubspec.lock
  pubspec.yaml
Labels: enhancement, hacktoberfest-accepted

#4 Feature/PKD-3
  images/2.0x/pokeball.png
  images/3.0x/pokeball.png
  images/pokeball.png
  lib/main.dart
  pubspec.yaml
Labels: enhancement, hacktoberfest-accepted

#5 Feature/PKD-4
  images/2.0x/pokeball_2.png
  images/3.0x/pokeball_2.png
  images/pokeball_2.png
  lib/classes/evolution.dart
  lib/classes/multiplier.dart
  lib/classes/pokemon.dart
  lib/classes/stat.dart
  lib/components/basic_info.dart
  lib/main.dart
  lib/network.dart
  lib/screens/details.dart
  lib/screens/home.dart
  lib/utils.dart
  pubspec.yaml
Labels: enhancement, hacktoberfest-accepted

#11 Bugfix/PKD-9
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/pokedex_secompp/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  ios/Runner.xcodeproj/project.pbxproj
  linux/CMakeLists.txt
  macos/Runner/Configs/AppInfo.xcconfig
  pubspec.yaml
  web/index.html
Labels: bug, hacktoberfest-accepted

#12 Release/1.0.1
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/pokedex_secompp/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  ios/Runner.xcodeproj/project.pbxproj
  linux/CMakeLists.txt
  macos/Runner/Configs/AppInfo.xcconfig
  pubspec.yaml
  web/index.html
Labels: release-merge

#13 Update evolution.dart
  lib/classes/evolution.dart
Labels: bug, hacktoberfest-accepted

#14 Bugfix/PKD-10
  lib/classes/evolution.dart
Labels: release-merge
